"use client";
import { useRef,useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { projects,experiences } from "@/data/portfolio";
import type {Copy} from "@/i18n/content"; import type {Locale} from "@/i18n/locales";
type Form={name:string;contact:string;subject:string;message:string}; const initial:Form={name:"",contact:"",subject:"",message:""};
export function Portfolio({locale,t}:{locale:Locale;t:Copy}){
 const router=useRouter();const [menu,setMenu]=useState(false),[method,setMethod]=useState<"email"|"sms">(locale==="fa"?"sms":"email"),[stage,setStage]=useState<"form"|"otp"|"success">("form"),[form,setForm]=useState(initial),[code,setCode]=useState(""),[challenge,setChallenge]=useState(""),[masked,setMasked]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);const otpRefs=useRef<Array<HTMLInputElement|null>>([]);
 const nav=["#home","#about","#projects","#experience","#contact"];const visitor=()=>{const k="ashkan_portfolio_visitor_id";let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v};const update=(key:keyof Form,value:string)=>setForm({...form,[key]:value});
 async function requestOtp(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");const contact=method==="sms"?form.contact.replace(/\s/g,"").replace(/^0/,"+98"):form.contact.trim();try{const r=await fetch("/api/contact/otp/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({method,contact,locale,visitorId:visitor(),honeypot:""})});const d=await r.json();if(!r.ok)throw Error(d.error);setChallenge(d.challengeId);setMasked(d.maskedDestination);setForm({...form,contact});setCode("");setStage("otp");setTimeout(()=>otpRefs.current[0]?.focus(),0)}catch(err){setNotice(err instanceof Error?err.message:"Unable to send verification code.")}finally{setBusy(false)}}
 async function sendMessage(token:string){setBusy(true);try{const r=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,locale,visitorId:visitor(),verificationToken:token,page:location.href,submissionAttemptId:crypto.randomUUID()})});const d=await r.json();if(!r.ok)throw Error(d.error);setStage("success")}catch(err){setNotice(err instanceof Error?err.message:"Unable to deliver your message.")}finally{setBusy(false)}}
 async function verifyOtp(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice("");try{const r=await fetch("/api/contact/otp/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({challengeId:challenge,code})});const d=await r.json();if(!r.ok)throw Error(d.error);await sendMessage(d.verificationToken)}catch(err){setNotice(err instanceof Error?err.message:"Verification failed.");setBusy(false)}}
 const setDigit=(i:number,v:string)=>{const digit=v.replace(/\D/g,"").slice(-1),next=code.split("");next[i]=digit;setCode(next.join("").slice(0,6));if(digit&&i<5)otpRefs.current[i+1]?.focus()};
 return <><header><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI</span></a><nav>{t.nav.map((x,i)=><a key={x} href={nav[i]}>{x}</a>)}</nav><div className="headtools"><select aria-label="Language" value={locale} onChange={e=>router.push(`/${e.target.value}${location.hash}`)}><option>EN</option><option>FA</option><option>FR</option><option>AR</option></select><button className="hamb" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?"×":"☰"}</button></div>{menu&&<div className="mobilemenu">{t.nav.map((x,i)=><a key={x} href={nav[i]} onClick={()=>setMenu(false)}>{x}</a>)}</div>}</header><main>
 <section id="home" className="hero"><div className="heroCopy"><p className="eyebrow">{t.intro}</p><h1>{t.hero}<br/><em>{t.accent}</em></h1><p className="lede">{t.bio}</p><p className="actions"><a className="btn primary" href="#projects">{t.work} ↗</a><a className="btn" href="#contact">{t.talk} ↗</a></p><div className="facts"><span><b>4</b> Selected products</span><span><b>2</b> Engineering degrees</span><span><b>Full-stack</b> Product delivery</span></div></div><div className="heroImg"><Image src="/images/hero/workspace.png" alt="Anonymous developer working at a desk with code monitors" fill priority sizes="(max-width:800px) 100vw,58vw"/><p>“Good software improves people’s lives.”</p></div></section>
 <section id="about" className="section about"><p className="marker">/ 01<br/>{t.about}</p><h2>{t.statement}</h2><div className="aboutcopy"><p>I’m Ashkan Giveki, a Senior Frontend Engineer with full-stack product experience. I turn complex requirements into maintainable web experiences across Next.js, React, TypeScript, Node.js, APIs, data and deployment infrastructure.</p><p>My workflow combines product thinking, thoughtful UI engineering, Spec-Driven Development and modern AI-assisted tools.</p></div><div className="orbit">From<br/><b>Ideas</b><br/>to Impact</div></section>
 <section id="projects" className="section"><p className="marker">/ 02<br/>{t.projects}</p><h2>{t.projects}</h2><div className="projects">{projects.map(([name,url,description,tags,tone])=><article className={`project ${tone}`} key={name}><div className="thumb"><b>{name}</b><span>{name==="LowBlock"?"Predict. Play. Compete.":name==="OnTyme"?"Time well spent.":name==="PaintStory"?"Small stories. Big imagination.":"A clearer path forward."}</span></div><h3>{name}<a href={url} target="_blank" rel="noopener noreferrer">↗</a></h3><p>{description}</p><div className="tags">{tags.map(x=><i key={x}>{x}</i>)}</div></article>)}</div></section>
 <section className="section skills"><p className="marker">/ 03<br/>SKILLS</p><h2>{t.skills}</h2><div className="skillgrid">{[["N","Next.js"],["⚛","React"],["TS","TypeScript"],["JS","Node.js"],["PG","PostgreSQL"],["M","MongoDB"],["◆","Docker"],["▲","Vercel"],["O","OpenSpec"],["▶","Playwright"],["~","Tailwind CSS"],["◆","Git"]].map(([icon,x])=><span key={x}><b className="skill-icon">{icon}</b>{x}</span>)}</div></section>
 <section id="experience" className="section"><p className="marker">/ 04<br/>{t.experience}</p><div className="timeline">{experiences.map(([date,role,company,description])=><article key={date}><i/><small>{date}</small><h3>{role}</h3><b>{company}</b><p>{description}</p></article>)}</div></section>
 <section id="contact" className="section contact"><div><p className="marker">/ 05<br/>{t.contact}</p><h2>{t.contactTitle}</h2><p className="lede">{t.contactText}</p></div><div className="formbox">{stage==="success"?<div className="success"><b>✓</b><h3>Message sent.</h3><p>Thank you — I’ll get back to you soon.</p></div>:stage==="otp"?<form onSubmit={verifyOtp}><p>We’ve sent a code to <b dir="ltr">{masked}</b>.</p><div className="otp-cells" role="group" aria-label="Six digit verification code">{Array.from({length:6},(_,i)=><input key={i} ref={el=>{otpRefs.current[i]=el}} value={code[i]||""} inputMode="numeric" autoComplete={i===0?"one-time-code":"off"} maxLength={1} aria-label={`Digit ${i+1}`} onChange={e=>setDigit(i,e.target.value)} onKeyDown={e=>{if(e.key==="Backspace"&&!code[i]&&i>0)otpRefs.current[i-1]?.focus()}} onPaste={e=>{e.preventDefault();const pasted=e.clipboardData.getData("text").replace(/\D/g,"").slice(0,6);setCode(pasted);otpRefs.current[Math.min(pasted.length,5)]?.focus()}} required/> )}</div><button className="btn primary" disabled={busy}>{busy?"Delivering…":"Verify & send"}</button><button type="button" className="text-button" onClick={()=>setStage("form")}>Change contact</button></form>:<form onSubmit={requestOtp}><div className="method"><button type="button" className={method==="sms"?"active":""} onClick={()=>setMethod("sms")}>Iran (+98 SMS)</button><button type="button" className={method==="email"?"active":""} onClick={()=>setMethod("email")}>International (Email)</button></div><label>Name<input required minLength={2} value={form.name} onChange={e=>update("name",e.target.value)}/></label><label>{method==="sms"?"Iranian mobile number":"Email"}<input required dir="ltr" value={form.contact} onChange={e=>update("contact",e.target.value)} placeholder={method==="sms"?"0912 123 4567":"your@email.com"}/></label><label>Subject<input required minLength={2} value={form.subject} onChange={e=>update("subject",e.target.value)}/></label><label>Message<textarea required minLength={10} value={form.message} onChange={e=>update("message",e.target.value)}/></label><button className="btn primary" disabled={busy}>{busy?"Sending code…":"Verify & send"}</button></form>}<p className="privacy" aria-live="polite">{notice||t.privacy}</p></div></section>
 </main><footer><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI<br/><small>Senior Frontend Engineer</small></span></a><div className="socials"><a href="https://github.com/AshkaanGiveki" aria-label="GitHub">◉</a><a href="https://linkedin.com/in/AshkanGiveki" aria-label="LinkedIn">in</a><a href="mailto:givekiashkaan@gmail.com" aria-label="Email">✉</a></div><p>© {new Date().getFullYear()} Ashkan Giveki</p></footer></>;
}
