"use client";
import { useRef, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { projects, experiences } from "@/data/portfolio";
import type { Copy } from "@/i18n/content";
import type { Locale } from "@/i18n/locales";
import { siDocker, siGithub, siGit, siMongodb, siNextdotjs, siNodedotjs, siPostgresql, siReact, siTailwindcss, siTypescript, siVercel, siPrisma, siFigma } from "simple-icons";
import type { SimpleIcon } from "simple-icons";
import LogoLoop from "./LogoLoop";

type Form = { name: string; contact: string; subject: string; message: string };
const initial: Form = { name: "", contact: "", subject: "", message: "" };
function Arrow({ up = false }: { up?: boolean }) { return <span className={up ? "arrow arrow-up" : "arrow"} aria-hidden="true">↗</span>; }
function Logo({ icon }: { icon: SimpleIcon }) { return <svg className="brand-icon" role="img" aria-label={icon.title} viewBox="0 0 24 24"><path d={icon.path} /></svg>; }
function LinkedInLogo() { return <svg className="brand-icon" role="img" aria-label="LinkedIn" viewBox="0 0 24 24"><path d="M20.45 20.45h-3.55v-5.57c0-1.33-.03-3.04-1.85-3.04-1.85 0-2.14 1.45-2.14 2.94v5.67H9.35V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.46v6.28ZM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12ZM3.56 20.45h3.56V9H3.56v11.45Z" /></svg>; }
function MailIcon() { return <svg className="brand-icon" viewBox="0 0 24 24" role="img" aria-label="Email"><path d="M2.5 5.5h19v13h-19v-13Zm2 2v.6l7.5 4.7 7.5-4.7v-.6H4.5Zm15 2.95-6.44 4.03a2 2 0 0 1-2.12 0L4.5 10.45v6.05h15v-6.05Z" /></svg>; }

export function Portfolio({ locale, t }: { locale: Locale; t: Copy }) {
  const router = useRouter(); const [menu, setMenu] = useState(false); const [method, setMethod] = useState<"email" | "sms">(locale === "fa" ? "sms" : "email"); const [stage, setStage] = useState<"form" | "otp" | "success">("form"); const [form, setForm] = useState(initial); const [code, setCode] = useState(""); const [challenge, setChallenge] = useState(""); const [masked, setMasked] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const otpRefs = useRef<Array<HTMLInputElement | null>>([]);
  const nav = ["#home", "#about", "#projects", "#experience", "#contact"];
  const visitor = () => { const key = "ashkan_portfolio_visitor_id"; let value = localStorage.getItem(key); if (!value) { value = crypto.randomUUID(); localStorage.setItem(key, value); } return value; };
  const update = (key: keyof Form, value: string) => setForm({ ...form, [key]: value });
  async function requestOtp(e: React.FormEvent) { e.preventDefault(); setBusy(true); setNotice(""); const contact = method === "sms" ? form.contact.replace(/\s/g, "").replace(/^0/, "+98") : form.contact.trim(); try { const response = await fetch("/api/contact/otp/request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ method, contact, locale, visitorId: visitor(), honeypot: "" }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setChallenge(data.challengeId); setMasked(data.maskedDestination); setForm({ ...form, contact }); setCode(""); setStage("otp"); setTimeout(() => otpRefs.current[0]?.focus(), 0); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to send verification code."); } finally { setBusy(false); } }
  async function sendMessage(token: string) { setBusy(true); try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, locale, visitorId: visitor(), verificationToken: token, page: location.href, submissionAttemptId: crypto.randomUUID() }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setStage("success"); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to deliver your message."); } finally { setBusy(false); } }
  async function verifyOtp(e: React.FormEvent) { e.preventDefault(); setBusy(true); setNotice(""); try { const response = await fetch("/api/contact/otp/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ challengeId: challenge, code }) }); const data = await response.json(); if (!response.ok) throw Error(data.error); await sendMessage(data.verificationToken); } catch (error) { setNotice(error instanceof Error ? error.message : "Verification failed."); setBusy(false); } }
  const setDigit = (index: number, value: string) => { const digit = value.replace(/\D/g, "").slice(-1); const next = code.split(""); next[index] = digit; setCode(next.join("").slice(0, 6)); if (digit && index < 5) otpRefs.current[index + 1]?.focus(); };
  const skillItems: Array<[SimpleIcon, string, string]> = [[siNextdotjs, "Next.js", "mono"], [siReact, "React", "react"], [siTypescript, "TypeScript", "ts"], [siNodedotjs, "Node.js", "node"], [siPostgresql, "PostgreSQL", "postgres"], [siMongodb, "MongoDB", "mongo"], [siDocker, "Docker", "docker"], [siVercel, "Vercel", "mono"], [siTailwindcss, "Tailwind CSS", "tailwind"], [siPrisma, "Prisma", "prisma"], [siGit, "Git", "git"], [siFigma, "Figma", "figma"]];
  return <div className="site-shell">
    <header className="site-header"><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI</span></a><nav>{t.nav.map((item, index) => <a className={index === 0 ? "active" : ""} key={item} href={nav[index]}>{item}</a>)}</nav><div className="headtools"><button className="language" aria-label="Language" onClick={() => router.push(`/${locale === "en" ? "fa" : "en"}${location.hash}`)}><span>◎</span> {locale.toUpperCase()} <small>⌄</small></button><button className="theme" aria-label="Toggle theme">◐</button><button className="hamb" onClick={() => setMenu(!menu)} aria-label="Menu"><span /><span /><span /></button></div>{menu && <div className="mobilemenu">{t.nav.map((item, index) => <a key={item} href={nav[index]} onClick={() => setMenu(false)}>{item}<Arrow /></a>)}</div>}</header>
    <main>
      <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">{t.intro}</p><h1>{t.hero}<br /><em>{t.accent}</em></h1><p className="lede">{t.bio}</p><div className="actions"><a className="btn primary" href="#projects">{t.work}<Arrow /></a><a className="btn" href="#contact">{t.talk}<Arrow /></a></div><div className="facts"><span><b>4</b><small>Shipped Products</small></span><span><b>5+</b><small>Years of Experience</small></span><span><b>10+</b><small>Happy Clients</small></span></div><div className="built-with"><small>BUILT WITH</small>{skillItems.slice(0, 3).map(([icon, name, color]) => <span className={color} key={name}><Logo icon={icon} />{name}</span>)}</div><div className="scroll-hint"><span>◯</span> Scroll Down</div></div><div className="hero-image"><Image src="/images/hero/workspace.png" alt="Developer working at a desk with code monitors" fill priority sizes="(max-width:800px) 100vw, 62vw" /><p>“Good software<br />improves people’s lives.”</p></div></section>
      <section id="about" className="section about"><div className="section-intro"><p className="marker">/ 01<br /><span>{t.about}</span></p><h2>{t.statement}</h2></div><div className="about-copy"><p>I’m Ashkan Giveki, a software engineer with a background in electrical engineering and a passion for building meaningful products at the intersection of technology, design, and human impact.</p><p className="about-meta">⌖ &nbsp; Based in Tehran, Iran &nbsp;·&nbsp; Open to remote opportunities worldwide</p></div><div className="orbit" aria-label="From ideas to impact"><span>From</span><b>Ideas</b><span>to Impact</span><i /></div></section>
      <section id="projects" className="section projects-section"><div className="section-heading"><p className="marker">/ 02<br /><span>{t.projects}</span></p><a href="#projects" className="view-all">View All Projects <Arrow /></a></div><div className="projects">{projects.map(([name, url, description, tags, tone]) => <article className={`project ${tone}`} key={name}><a className="thumb" href={url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${name}`}><span className="thumb-title">{name}</span><strong>{name === "LowBlock" ? "Play\nPredict\nCompete" : name === "OnTyme" ? "Time\nwell spent." : name === "PaintStory" ? "Small stories.\nBig imagination." : "A calmer\nbright future."}</strong><span className="mobile-preview-copy"><b>{name}</b><small>{name === "Neuroca" ? "AI-powered mental wellness companion." : description.split(" with ")[0] + "."}</small><span className="tags">{tags.slice(0, 3).map(tag => <i key={tag}>{tag}</i>)}</span></span></a><div className="project-content"><h3>{name}<a href={url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${name}`}><Arrow /></a></h3><p>{description}</p><div className="tags">{tags.map(tag => <i key={tag}>{tag}</i>)}</div></div></article>)}</div></section>
      <section className="section skills"><div className="skills-copy"><p className="marker">/ 03<br /><span>SKILLS</span></p><h2>{t.skills}</h2></div><div className="skill-loops">{([[6, "desktop"], [4, "tablet"], [3, "mobile"]] as const).map(([size, mode]) => Array.from({ length: Math.ceil(skillItems.length / size) }, (_, row) => <LogoLoop key={`${mode}-${row}`} className={`tools-loop tools-loop-${mode}`} logos={skillItems.slice(row * size, row * size + size).map(([icon, name, color]) => ({ icon, name, color }))} speed={36} direction={row % 2 ? "right" : "left"} logoHeight={24} gap={30} pauseOnHover fadeOut fadeOutColor="#071114" scaleOnHover ariaLabel={`${mode} technology tools`} renderItem={(item: { icon: SimpleIcon; name: string; color: string }) => <span className={`loop-tool ${item.color}`}><Logo icon={item.icon} /><small>{item.name}</small></span>} />))}</div></section>
      <section id="experience" className="section experience"><div className="section-intro"><p className="marker">/ 04<br /><span>{t.experience}</span></p></div><div className="timeline">{experiences.map(([date, role, company, description], index) => <article key={`${date}-${company}`} className={index === 0 ? "current" : ""}><i /><small>{date}</small><h3>{role}</h3><b>{company}</b><p>{description}</p></article>)}</div><div className="experience-quote"><span>“</span><p>Continuous<br />learning,<br /><em>better products.</em></p><i /></div></section>
      <section id="contact" className="section contact"><div className="contact-copy"><p className="marker">/ 05<br /><span>{t.contact}</span></p><h2>{t.contactTitle}</h2><p className="lede">{t.contactText}</p></div><div className="formbox">{stage === "success" ? <div className="success"><b>✓</b><h3>Message sent.</h3><p>Thank you — I’ll get back to you soon.</p></div> : stage === "otp" ? <form onSubmit={verifyOtp}><p>We’ve sent a code to <b dir="ltr">{masked}</b>.</p><div className="otp-cells" role="group" aria-label="Six digit verification code">{Array.from({ length: 6 }, (_, index) => <input key={index} ref={element => { otpRefs.current[index] = element; }} value={code[index] || ""} inputMode="numeric" autoComplete={index === 0 ? "one-time-code" : "off"} maxLength={1} aria-label={`Digit ${index + 1}`} onChange={e => setDigit(index, e.target.value)} required />)}</div><button className="btn primary" disabled={busy}>{busy ? "Delivering…" : "Verify & send"}</button><button type="button" className="text-button" onClick={() => setStage("form")}>Change contact</button></form> : <form onSubmit={requestOtp}><div className="method"><button type="button" className={method === "sms" ? "active" : ""} onClick={() => setMethod("sms")}>Iran (+98 SMS)</button><button type="button" className={method === "email" ? "active" : ""} onClick={() => setMethod("email")}>International (Email)</button></div><div className="form-row"><label>Name<input required minLength={2} value={form.name} onChange={e => update("name", e.target.value)} /></label><label>{method === "sms" ? "Iranian mobile number" : "Email"}<input required dir="ltr" value={form.contact} onChange={e => update("contact", e.target.value)} placeholder={method === "sms" ? "0912 123 4567" : "your@email.com"} /></label></div><label>Subject<input required minLength={2} value={form.subject} onChange={e => update("subject", e.target.value)} /></label><label>Message<textarea required minLength={10} value={form.message} onChange={e => update("message", e.target.value)} /></label><button className="btn primary" disabled={busy}>{busy ? "Sending code…" : "Send Message"}<Arrow /></button></form>}<p className="privacy" aria-live="polite">{notice || t.privacy}</p></div></section>
    </main>
    <footer><div className="footer-main"><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI<br /><small>Senior Frontend Engineer</small></span></a><div className="footer-nav">{t.nav.map((item, index) => index === 3 ? null : <a key={item} href={nav[index]}>{item}</a>)}</div><div className="socials"><a href="https://github.com/AshkaanGiveki" aria-label="GitHub"><Logo icon={siGithub} /></a><a href="https://linkedin.com/in/AshkanGiveki" aria-label="LinkedIn"><LinkedInLogo /></a><a href="mailto:givekiashkaan@gmail.com" aria-label="Email"><MailIcon /></a></div><p className="footer-quote">“A more human internet<br />is a brighter future.”</p></div><div className="footer-bottom"><p>© {new Date().getFullYear()} Ashkan Giveki. All rights reserved.</p><div><a className="backtop" href="#home" aria-label="Back to top"><Arrow up /></a></div></div></footer>
  </div>;
}
