"use client";
import { useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { projects, experiences } from "@/data/portfolio";
import type { Copy } from "@/i18n/content";
import type { Locale } from "@/i18n/locales";

type FormValues = { name: string; contact: string; subject: string; message: string };
const empty: FormValues = { name: "", contact: "", subject: "", message: "" };

export function Portfolio({ locale, t }: { locale: Locale; t: Copy }) {
  const [menu, setMenu] = useState(false); const [method, setMethod] = useState<"email" | "sms">(locale === "fa" ? "sms" : "email");
  const [stage, setStage] = useState<"form" | "otp" | "verified" | "success">("form"); const [values, setValues] = useState(empty); const [code, setCode] = useState(""); const [challenge, setChallenge] = useState(""); const [token, setToken] = useState(""); const [masked, setMasked] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const router = useRouter(); const lang = (v: string) => { router.push(`/${v}${location.hash}`); };
  const update = (key: keyof FormValues, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const visitor = () => { const key = "ashkan_portfolio_visitor_id"; let id = localStorage.getItem(key); if (!id) { id = crypto.randomUUID(); localStorage.setItem(key, id); } return id; };
  async function requestOtp(event: React.FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); const contact = method === "sms" ? values.contact.replace(/\s/g, "").replace(/^0/, "+98") : values.contact.trim(); try { const response = await fetch("/api/contact/otp/request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ method, contact, locale, visitorId: visitor(), honeypot: "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setChallenge(data.challengeId); setMasked(data.maskedDestination); setValues({ ...values, contact }); setStage("otp"); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to send verification code."); } finally { setBusy(false); } }
  async function verifyOtp(event: React.FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); try { const response = await fetch("/api/contact/otp/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ challengeId: challenge, code }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setToken(data.verificationToken); setStage("verified"); setNotice("Contact verified ✓"); } catch (error) { setNotice(error instanceof Error ? error.message : "Verification failed."); } finally { setBusy(false); } }
  async function submitMessage(event: React.FormEvent) { event.preventDefault(); setBusy(true); setNotice(""); try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, locale, visitorId: visitor(), verificationToken: token, page: location.href, submissionAttemptId: crypto.randomUUID() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setStage("success"); } catch (error) { setNotice(error instanceof Error ? error.message : "Unable to send your message."); } finally { setBusy(false); } }
  const nav = ["#home", "#about", "#projects", "#experience", "#contact"];
  return <><header><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI</span></a><nav>{t.nav.map((n, i) => <a key={n} href={nav[i]}>{n}</a>)}</nav><div className="headtools"><select value={locale} onChange={(e) => lang(e.target.value)} aria-label="Language"><option value="en">EN</option><option value="fa">FA</option><option value="fr">FR</option><option value="ar">AR</option></select><button className="hamb" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-label="Menu">{menu ? "×" : "☰"}</button></div>{menu && <div className="mobilemenu">{t.nav.map((n, i) => <a onClick={() => setMenu(false)} key={n} href={nav[i]}>{n}</a>)}</div>}</header><main>
    <section id="home" className="hero"><div className="heroCopy"><p className="eyebrow">{t.intro}</p><h1>{t.hero}<br /><em>{t.accent}</em></h1><p className="lede">{t.bio}</p><p className="actions"><a className="btn primary" href="#projects">{t.work} ↗</a><a className="btn" href="#contact">{t.talk} ↗</a></p><div className="facts"><span><b>4</b> Selected products</span><span><b>2</b> Engineering degrees</span><span><b>Full-stack</b> Product delivery</span></div></div><div className="heroImg"><Image src="/images/hero/workspace.png" alt="Anonymous developer working at a desk with code monitors" fill priority sizes="(max-width: 800px) 100vw, 58vw" /><p>“Good software improves people’s lives.”</p></div></section>
    <section id="about" className="section about"><p className="marker">/ 01<br />{t.about}</p><h2>{t.statement}</h2><div className="aboutcopy"><p>I’m Ashkan Giveki, a Senior Frontend Engineer with full-stack product experience. I turn complex requirements into maintainable web experiences across Next.js, React, TypeScript, Node.js, APIs, data and deployment infrastructure.</p><p>My workflow combines product thinking, thoughtful UI engineering, Spec-Driven Development and modern AI-assisted tools.</p></div><div className="orbit">From<br /><b>Ideas</b><br />to Impact</div></section>
    <section id="projects" className="section"><p className="marker">/ 02<br />{t.projects}</p><h2>{t.projects}</h2><div className="projects">{projects.map(([name, url, description, tags, tone]) => <article className={`project ${tone}`} key={name}><div className="thumb"><b>{name}</b><span>{name === "LowBlock" ? "Predict. Play. Compete." : name === "OnTyme" ? "Time well spent." : name === "PaintStory" ? "Small stories. Big imagination." : "A clearer path forward."}</span></div><h3>{name}<a href={url} target="_blank" rel="noopener noreferrer" aria-label={`Visit ${name}`}>↗</a></h3><p>{description}</p><div className="tags">{tags.map((x) => <i key={x}>{x}</i>)}</div></article>)}</div></section>
    <section className="section skills"><p className="marker">/ 03<br />SKILLS</p><h2>{t.skills}</h2><div className="skillgrid">{["Next.js", "React", "TypeScript", "Node.js", "PostgreSQL", "MongoDB", "Docker", "Vercel", "OpenSpec", "Playwright", "Tailwind CSS", "Git"].map((x) => <span key={x}>{x}</span>)}</div></section>
    <section id="experience" className="section"><p className="marker">/ 04<br />{t.experience}</p><div className="timeline">{experiences.map(([date, role, company, description]) => <article key={date}><i /><small>{date}</small><h3>{role}</h3><b>{company}</b><p>{description}</p></article>)}</div></section>
    <section id="contact" className="section contact"><div><p className="marker">/ 05<br />{t.contact}</p><h2>{t.contactTitle}</h2><p className="lede">{t.contactText}</p></div><div className="formbox">{stage === "success" ? <div className="success"><b>✓</b><h3>Message sent.</h3><p>Thank you — I’ll get back to you soon.</p></div> : stage === "otp" ? <form onSubmit={verifyOtp}><p>We’ve sent a code to <b dir="ltr">{masked}</b>.</p><label>6-digit verification code<input autoFocus inputMode="numeric" autoComplete="one-time-code" value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))} required pattern="[0-9]{6}" /></label><button className="btn primary" disabled={busy}>{busy ? "Verifying…" : "Verify code ↗"}</button><button type="button" className="text-button" onClick={() => setStage("form")}>Change contact</button></form> : <form onSubmit={stage === "verified" ? submitMessage : requestOtp}><div className="method"><button type="button" className={method === "sms" ? "active" : ""} onClick={() => setMethod("sms")}>Iran (+98 SMS)</button><button type="button" className={method === "email" ? "active" : ""} onClick={() => setMethod("email")}>International (Email)</button></div><label>Name<input required minLength={2} value={values.name} onChange={(e) => update("name", e.target.value)} /></label><label>{method === "sms" ? "Iranian mobile number" : "Email"}<input required dir="ltr" value={values.contact} onChange={(e) => update("contact", e.target.value)} placeholder={method === "sms" ? "0912 123 4567" : "your@email.com"} /></label><label>Subject<input required minLength={2} value={values.subject} onChange={(e) => update("subject", e.target.value)} /></label><label>Message<textarea required minLength={10} value={values.message} onChange={(e) => update("message", e.target.value)} /></label>{stage === "verified" && <p className="verified">Contact verified ✓</p>}<button className="btn primary" disabled={busy}>{busy ? "Working…" : stage === "verified" ? "Send message ↗" : "Verify & send ↗"}</button></form>}<p className="privacy" aria-live="polite">{notice || t.privacy}</p></div></section>
  </main><footer><a className="brand" href="#home"><b>AG</b><span>ASHKAN GIVEKI<br /><small>Senior Frontend Engineer</small></span></a><div><a href="https://github.com/AshkaanGiveki">GitHub</a><a href="https://linkedin.com/in/AshkanGiveki">LinkedIn</a></div><p>© {new Date().getFullYear()} Ashkan Giveki</p></footer></>;
}
